### ISSUE TITLE
Too many modules

### ISSUE THREAD

**Issue by penn5** [friendly-telegram/friendly-telegram#12]
We are on the verge of getting actively bloated. I propose to move non-core modules to an external module, and add an easy module to download these external modules. Once loaded, they must live in the modules/ directory, and they must persist heroku restarts and updates, ideally without making a git commit. This could be implemented with a config value containing URLs to load after client is initialised.

**Comment by sahyam** [comment]
@penn5 Ok

**Comment by AvinashReddy3108** [comment]
> We are on the verge of getting actively bloated. I propose to move non-core modules to an external module, and add an easy module to download these external modules. Once loaded, they must live in the modules/ directory, and they must persist heroku restarts and updates, ideally without making a git commit. This could be implemented with a config value containing URLs to load after client is initialised.

IDK about the restart persistence, but we can hack the init script of the userbot to download all module URL's defined in the config value.
[Users can be given a template repo with minimal examples to host new modules for the userbot]

**Comment by penn5** [comment]
@AvinashReddy3108 Don't worry, I have a plan and it's almost done
