### ISSUE TITLE
SQL based modules won't work

### ISSUE THREAD

**Issue by loque036** [friendly-telegram/friendly-telegram#15]
Can't load paperplane modules that depend on SQL

**Comment by AvinashReddy3108** [comment]
> Can't load paperplane modules that depend on SQL

As far as the Paperplane stuff goes, SQL dependent modules have a separate `sql_helper` for them. (like for notes, they have /userbot/modules/sql_helper/notes_sql.py), which the compat layer in FTG cannot handle as of now.

**Comment by penn5** [comment]
> > Can't load paperplane modules that depend on SQL
> 
> As far as the Paperplane stuff goes, SQL dependent modules have a separate `sql_helper` for them. (like for notes, they have /userbot/modules/sql_helper/notes_sql.py), which the compat layer in FTG cannot handle as of now.

I know lol

**Comment by penn5** [comment]
Ugh, i don't know if i can fix this. PPE is so badly designed (xD)

**Comment by penn5** [comment]
It is a bug but i can't fix it.
