### ISSUE TITLE
Help command gets too big after importing a few modules

### ISSUE THREAD

**Issue by loque036** [friendly-telegram/friendly-telegram#24]
Make help command smaller because after a few modules it becomes 2 messages and it's spammy and gets too bloated

**Comment by penn5** [comment]
Remove commands and just have list of modules?

**Comment by SpEcHiDe** [comment]
@penn5 use an inline bot and clicking on the buttons gets you the relevant help. 🤪😜😜😬

**Comment by penn5** [comment]
@SpEcHiDe No, that's very hacky. If telegram enable buttons for users I would do that but I don't want excessive complexity

**Comment by penn5** [comment]
@loque036 how should i do this?

**Comment by penn5** [comment]
Fixed by a30b2e1aab88b4738d31a8e73e643621b291a6db
