### ISSUE TITLE
Dlmod 

### ISSUE THREAD

**Issue by iamd7h** [friendly-telegram/friendly-telegram#29]
I don’t know if this is a bug or what but downloaded modules are disappearing after restarting a bot or after some time.

**Comment by penn5** [comment]
@iamd7h thats not possible.

**Comment by iamd7h** [comment]
@penn5 But it is , i downloaded scrapers.py twice already today itself but it got unloaded on its own

**Comment by penn5** [comment]
@iamd7h Logs or it doesn't exist

**Comment by iamd7h** [comment]
@penn5 How do i send the logs ? Because when i run the command it becomes a normal message cause the module isn’t there

**Comment by penn5** [comment]
@iamd7h Your logs show heroku uninstalled the dependencies of these modules. It usually does this around once per day

**Comment by iamd7h** [comment]
@penn5 And can it be fixed?

**Comment by penn5** [comment]
@iamd7h Fork repo and edit requirements.txt is the only fix, but then pulling updates will go awry
