### ISSUE TITLE
showing error on pythonanywhere.com

### ISSUE THREAD

**Issue by rsoorajs** [friendly-telegram/friendly-telegram#48]
while using 

$(which curl>/dev/null&&echo curl -LsO||echo wget -q) https://git.io/JeOXn&&(. JeOXn);rm JeOXn

this command on pythonanywhere.com.it showing the below error.

[Click here](https://telegra.ph/file/66ab139e6c1bbb5cbc2df.jpg)

**Comment by penn5** [comment]
Unable to reproduce error, although there appears to be a firewall blocking connections to Telegram servers.
