### ISSUE TITLE
Uniborg compat error

### ISSUE THREAD

**Issue by erenmetesar** [friendly-telegram/friendly-telegram#51]
[ftg-logs.txt](https://del.dog/xudehisesi) 

[warnbun.py](https://raw.githubusercontent.com/ravana69/PornHub/master/stdplugins/warnbun.py)

**Comment by penn5** [comment]
fixed in https://github.com/friendly-telegram/friendly-telegram/commit/4ecda42f38ad56fd696259d4a77077187bb58bb5
