### ISSUE TITLE
Unloadmod

### ISSUE THREAD

**Issue by erenmetesar** [friendly-telegram/friendly-telegram#53]
It can't unload external modules, they come back after a restart. Unfortunately, no error logs.

**Comment by penn5** [comment]
Found cause - friendly-telegram.modules.https://raw_githubusercontent_com/AvinashReddy3108/PaperplaneExtended/50fff1520af35237c9975e4c0ff74a3419dce0f8/userbot/modules/memes_py

Needs a . but we can't put it. Will fix at weekend

**Comment by penn5** [comment]
Closed by https://github.com/friendly-telegram/friendly-telegram/commit/1ca59756cc5830d09c60cc6ee373a7f2e15a3c81
