### ISSUE TITLE
where is purge modules? i wanna kang it

### ISSUE THREAD

**Issue by x007R** [friendly-telegram/friendly-telegram#54]

**Comment by penn5** [comment]
Surprisingly, the purge module is in purge.py. May I remind you we use the AGPL license so kanging is illegal.

**Comment by x007R** [comment]
where?? are u joking me?
![image](https://user-images.githubusercontent.com/53249888/67943292-55c08c00-fc0c-11e9-9b01-0401d62811f2.png)

**Comment by x007R** [comment]
???
