### ISSUE TITLE
Clear saved Notes and get the list of saved notes

### ISSUE THREAD

**Issue by DrPhilosophus** [friendly-telegram/friendly-telegram#62]
There are **group manager bots**  available for notes module. But the notes module in the ftg userbot is very much useful in Telegram's **saved messages**  in which you can't add bots.

Can you add **clearing saved notes**  and **getting the list of notes**  feature to the _notes module_ ?

**Comment by penn5** [comment]
fixed in 37fa8ffb6187a976b50231ad29fa1db2e3fe8d41
