### ISSUE TITLE
.help broknnn

### ISSUE THREAD

**Issue by old-izayoi** [friendly-telegram/friendly-telegram#66]
ftg broke 

ERROR:root:Command failed Traceback (most recent call last): File "/root/friendly-telegram/friendly-telegram/main.py", line 130, in handle_command await coro File "/root/friendly-telegram/friendly-telegram/modules/help.py", line 68, in helpcmd reply += _("\n• <b>{}</b> ({})").format(mod.name, len(mod.commands)) AttributeError: 'SpamMod' object has no attribute 'commands' ERROR:telethon.client.updates:Unhandled exception on functools.partial(<function handle_command at 0x7fcbc49e29d8>, <friendly-telegram.loader.Modules object at 0x7fcbc01f4160>, <friendly-telegram.database.frontend.Database object at 0x7fcbc02b2fc0>) Traceback (most recent call last): File "/root/.local/lib/python3.7/site-packages/telethon/client/updates.py", line 422, in _dispatch_update await callback(event) File "/root/friendly-telegram/friendly-telegram/main.py", line 138, in handle_command raise e File "/root/friendly-telegram/friendly-telegram/main.py", line 130, in handle_command await coro File "/root/friendly-telegram/friendly-telegram/modules/help.py", line 68, in helpcmd reply += _("\n• <b>{}</b> ({})").format(mod.name, len(mod.commands)) AttributeError: 'SpamMod' object has no attribute 'commands'

**Comment by penn5** [comment]
Not reproduceable.
