### ISSUE TITLE
Missing closing tags in some localization strings

### ISSUE THREAD

**Issue by mashed-potatoes** [friendly-telegram/friendly-telegram#75]
- `updater:success_meme`
 - `notes:what_name`
 - `system info:os` (no `>` symbol)

**Comment by AvinashReddy3108** [comment]
Thanks for letting us know of this.

The derps for the notes and system info have been patched, reload those modules for getting the fix.

A pull request for the updater patch has been created, will be merged when @penn5 is online.

**Comment by mashed-potatoes** [comment]
Thank you!
