### ISSUE TITLE
Downloader module request

### ISSUE THREAD

**Issue by mishailovic** [friendly-telegram/friendly-telegram#78]
I have an idea for a module, but unfortunately I can’t program well.  The essence of the module is that it allows you to upload files and videos to telegrams without downloading from to your phone.  e.g. .upload youtube.com/someone'svideo downloads this video and uploads it to telegram.  You can connect the YouTube-dl library and it will work with any sites.

**Comment by hjyoung1** [comment]
For new module ideas use this issue
https://github.com/friendly-telegram/modules-repo/issues/11
